import os
from dotenv import load_dotenv
from airflow.utils.email import send_email

load_dotenv()

def send_alphrid_charts_email(output_dir, **context):
    subject = "ALPHRID Daily Productivity Charts"
    body = "Attached are your productivity visualizations generated by ALPHRID."

    recipient_email = os.getenv("ALPHRID_REPORT_EMAIL")
    if not recipient_email:
        raise ValueError("Missing ALPHRID_REPORT_EMAIL in environment variables")

    # Grab all PNGs from output_dir
    attachments = [
        os.path.join(output_dir, file)
        for file in os.listdir(output_dir)
        if file.endswith(".png")
    ]

    if not attachments:
        raise FileNotFoundError("No chart PNGs found in output_dir.")

    send_email(
        to=[recipient_email], 
        subject=subject,
        html_content=body,
        files=attachments,
        conn_id="smtp_default"
    )